# Configuration for xFinder model
xfinder_model:
  model_name: "xFinder-llama38it"        # must have, xFinder-qwen1505 or xFinder-llama38it
  model_path: "/mnt/hwfile/optimal/chenpengan/xFinder-llama38it"  # path to the model, only need if use local deployment
  # url: "API-url/to/xFinder-model"       # url to the model, only need if use remote deployment

# Configuration for data file
# data_path: "/mnt/petrelfs/chenpengan/xFinder/demo/example.json"        # path to the data which need to be evaluated
data_path: "/mnt/petrelfs/chenpengan/xFinder/CantoneseBenchmark/converted_GSM8K_yue"